# Generated by Django 3.0.8 on 2020-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainView', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmanswer',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
